#!/usr/bin/env bash
# This Script displays numbers from 1 to 100. with Fizzbuzz

for((a=1; a <101; a++))
do
    if((a%15 == 0));
    then
        echo "Fizzbuzz"
    elif((a%3 == 0));
    then
        echo "Fizz"
    elif((a%5 == 0));
    then
        echo "Buzz"
    else
        echo "$a"
    fi
done
