#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes: using a while loop
count=0
while [ $count -le 12 ]
do
    echo "Hours: $count"
    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        ((minute++))
    done
    ((count++))
done
